from enum import Enum


class IntegrationServiceIdentifier(str, Enum):
    MACONOMY_CASEWARE_CLOUD_SYNC = "MACONOMY_CASEWARE_CLOUD_SYNC"
    MACONOMY_CCH_XCM_TASK_MAPPING = "MACONOMY_CCH_XCM_TASK_MAPPING"
    MACONOMY_CCH_XCM_CLIENT_SCOPED = "MACONOMY_CCH_XCM_CLIENT_SCOPED"

    #paycor constants
    PAYCOR_SYNC_ONBOARDING_EMPLOYEES = "PAYCOR_SYNC_ONBOARDING_EMPLOYEES"
