from enum import Enum


class IntegrationServiceIdentifier(str, Enum):
    CASEWARE_CREATE_ENGAGEMENT = "CASEWARE_CREATE_ENGAGEMENT"
    CASEWARE_SYNC_CREATED_ENGAGEMENTS = "CASEWARE_SYNC_CREATED_ENGAGEMENTS"
    CASEWARE_UPDATE_ENGAGEMENT = "CASEWARE_UPDATE_ENGAGEMENT"
    CASEWARE_SYNC_UPDATED_ENGAGEMENTS = "CASEWARE_SYNC_UPDATED_ENGAGEMENTS"
