"""20260916_0009_rename_expensesheet_number_to_report_id

Revision ID: 3563461727f9
Revises: 9f15f1c98ec9
Create Date: 2026-09-16 15:39:08.988004
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3563461727f9'
down_revision: Union[str, None] = '9f15f1c98ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sap_concur_integration_logs', sa.Column('report_id', sa.Text(), nullable=False))
    op.drop_column('sap_concur_integration_logs', 'expensesheet_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sap_concur_integration_logs', sa.Column('expensesheet_number', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('sap_concur_integration_logs', 'report_id')
    # ### end Alembic commands ###
