"""add paycor integration models

Revision ID: 8b29928452bc
Revises: 20260831_0008
Create Date: 2026-08-31 18:17:02.887498
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b29928452bc'
down_revision: Union[str, None] = '20260831_0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paycor_employee_mapping_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paycor_onboarding_employee_id', sa.Uuid(), nullable=False),
    sa.Column('paycor_legal_entity_id', sa.Integer(), nullable=False),
    sa.Column('paycor_employee_number', sa.Text(), nullable=True),
    sa.Column('maconomy_employee_number', sa.Text(), nullable=True),
    sa.Column('employee_status', sa.Enum('INVITED', 'HIRED', name='paycor_employee_status'), nullable=False),
    sa.Column('created_on_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paycor_employee_mapping_log')),
    sa.UniqueConstraint('paycor_legal_entity_id', 'paycor_onboarding_employee_id', name='uq_paycor_mapping_legal_entity_onboarding_employee')
    )
    op.create_table('paycor_integration_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paycor_employee_mapping_log_id', sa.Uuid(), nullable=True),
    sa.Column('paycor_onboarding_employee_id', sa.Uuid(), nullable=False),
    sa.Column('instance', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='paycor_integration_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', name='paycor_integration_action'), nullable=False),
    sa.Column('created_on_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paycor_employee_mapping_log_id'], ['paycor_employee_mapping_log.id'], name=op.f('fk_paycor_integration_logs_paycor_employee_mapping_log_id_paycor_employee_mapping_log')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paycor_integration_logs'))
    )
    op.alter_column('caseware_cloud_entity_engagement_mapping', 'maconomy_job_version_number',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('caseware_cloud_entity_engagement_mapping', 'maconomy_job_version_number',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_table('paycor_integration_logs')
    op.drop_table('paycor_employee_mapping_log')
    # ### end Alembic commands ###
