"""add employee number to mapping

Revision ID: 8bab87a49c0e
Revises: 20260831_0008
Create Date: 2026-09-10 15:05:50.522047
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8bab87a49c0e'
down_revision: Union[str, None] = 'a8c4bafd2f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sap_concur_expensesheet_expensereport_mapping', sa.Column('maconomy_employee_number', sa.Text(), nullable=True))
    op.add_column('sap_concur_integration_logs', sa.Column('employeeemail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sap_concur_integration_logs', 'employeeemail')
    op.drop_column('sap_concur_expensesheet_expensereport_mapping', 'maconomy_employee_number')
    # ### end Alembic commands ###
