"""add metadata to mapping in expense mapping

Revision ID: 9f15f1c98ec9
Revises: 8bab87a49c0e
Create Date: 2026-09-10 19:53:11.818612
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9f15f1c98ec9'
down_revision: Union[str, None] = '8bab87a49c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sap_concur_expensesheet_expensereport_mapping', sa.Column('expense_line_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sap_concur_expensesheet_expensereport_mapping', 'expense_line_metadata')
    # ### end Alembic commands ###
