"""sap_concur_integration and mapping models

Revision ID: a8c4bafd2f52
Revises: 20260822_0007
Create Date: 2026-09-04 15:29:50.226712
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8c4bafd2f52'
down_revision: Union[str, None] = '20260822_0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_concur_expensesheet_expensereport_mapping',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('maconomy_expensesheet_no', sa.Text(), nullable=False),
    sa.Column('sap_concur_expensereport_id', sa.Text(), nullable=False),
    sa.Column('created_on_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sap_concur_expensesheet_expensereport_mapping'))
    )
    op.create_table('sap_concur_integration_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sap_concur_expensesheet_expensereport_mapping_id', sa.Uuid(), nullable=True),
    sa.Column('instance', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'SKIPPED', name='sap_concur_integration_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', name='sap_concur_integration_action'), nullable=False),
    sa.Column('expensesheet_number', sa.Text(), nullable=False),
    sa.Column('created_on_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sap_concur_expensesheet_expensereport_mapping_id'], ['sap_concur_expensesheet_expensereport_mapping.id'], name=op.f('fk_sap_concur_integration_logs_sap_concur_expensesheet_expensereport_mapping_id_sap_concur_expensesheet_expensereport_mapping')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sap_concur_integration_logs'))
    )
    op.alter_column('caseware_cloud_entity_engagement_mapping', 'maconomy_job_version_number',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('caseware_cloud_entity_engagement_mapping', 'maconomy_job_version_number',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_table('sap_concur_integration_logs')
    op.drop_table('sap_concur_expensesheet_expensereport_mapping')
    # ### end Alembic commands ###
