"""add maconomy job version number column

Revision ID: b474bb1bb412
Revises: cd312664b17e
Create Date: 2026-08-19 15:13:34.592915
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b474bb1bb412'
down_revision: Union[str, None] = 'cd312664b17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caseware_cloud_entity_engagement_mapping', sa.Column('maconomy_job_version_number', sa.Text(), nullable=False, default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caseware_cloud_entity_engagement_mapping', 'maconomy_job_version_number')
    # ### end Alembic commands ###
